<?php
namespace DDDGen\Tests;

use DDDGenApp\Input\Console\Commands\Generate;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\Output;

class ConsoleGeneratorTest extends TestCase
{
    protected function tearDown()
    {
        // remove all tmp folders
        passthru("rm -rf " . __DIR__ . "/resources/tmp");
        
        parent::tearDown(); // TODO: Change the autogenerated stub
        
    }
    
    
    function test_it_generates_files_from_console_command()
    {
        $config_path = __DIR__ . "/resources/console.config.php";
        $config_array = require($config_path);
        
        $command     = "generate ";
        $command     .= " app command Account/Login ";
        $command     .= " -y -c " . $config_path;
        
        $input  = new StringInput($command);
        $output = new TestOutput();
        
        //
        // Init console app
        //
        $application = new Application();
        $application->add(new Generate());
        $application->doRun($input, $output);
        
        //
        // Assert that files are in place
        //
        $this->assertTrue(file_exists($config_array['layers']['app']['src']['dir']."/Account/Login/LoginCommand.php"));
        $this->assertTrue(file_exists($config_array['layers']['app']['src']['dir']."/Account/Login/LoginHandler.php"));
        $this->assertTrue(file_exists($config_array['layers']['app']['tests']['dir']."/Account/Login/LoginCommandTest.php"));
    }
    
}


class TestOutput extends Output
{
    public $output = '';
    
    public function clear()
    {
        $this->output = '';
    }
    
    protected function doWrite($message, $newline)
    {
        $this->output .= $message . ($newline ? "\n" : '');
    }
}
